TOPDIR=../..

SOURCES = \
	CubeSensorModel.cpp\
	GrabberModel.cpp\
	IntakeModel.cpp\
	LifterModel.cpp\
	OIModel.cpp\
	PhoenixScreenVisualizer.cpp\
	PhoenixSimulator.cpp\
	WingsModel.cpp

TARGET=phoenixsim

NEED_WPILIB=true
NEED_CTRE=true
NEED_NAVX=true
NEED_XEROMISC=true
NEED_XEROMATH=true

LOCAL_CFLAGS +=

include $(TOPDIR)/makefiles/buildlib.mk

