SOURCES = \
	ActionSequence.cpp\
	ControllerBase.cpp\
	DelayAction.cpp\
	DispatchAction.cpp\
	Drivebase.cpp\
	Robot.cpp\
	Subsystem.cpp\
	tankdrive/TankDrive.cpp\
	tankdrive/TankDriveDistanceAction.cpp\
	tankdrive/TankDriveVelocityAction.cpp\
	tankdrive/TankDriveCharAction.cpp

TARGET=gopigo3xerobase

LOCAL_CFLAGS = -I. -I../gopigo3/gopigo3navx -I../gopigo3/gopigo3hw -I../gopigo3/gopigo3frc -I../xeromath -I../xeromisc

include ../makefiles/gopilib.mk
