SOURCES = \
	ActionSequence.cpp\
	ControllerBase.cpp\
	DelayAction.cpp\
	DispatchAction.cpp\
	DriverGamepad.cpp\
	OIDevice.cpp\
	OIOutputAction.cpp\
	OISubsystem.cpp\
	ParallelAction.cpp\
	Robot.cpp\
	RobotSubsystem.cpp\
	Subsystem.cpp\
	TCS34725ColorSensor.cpp\
	TeleopController.cpp\
	MessageListener/MessageListener.cpp\
	tankdrive/TankDrive.cpp\
	tankdrive/TankDriveDistanceAction.cpp\
	tankdrive/TankDriveVelocityAction.cpp\
	tankdrive/TankDriveCharAction.cpp\
	tankdrive/TankDriveAngleAction.cpp\
	tankdrive/TankDriveAngleCharAction.cpp\
	tankdrive/TankDrivePowerAction.cpp\
	tankdrive/TankDriveTimedPowerAction.cpp

TARGET=gopigo3xerobase

LOCAL_CFLAGS = -I. -I../gopigo3 -I../gopigo3/gopigo3navx -I../gopigo3/gopigo3hw -I../gopigo3/frc -I../xeromath -I../xeromisc

include ../makefiles/gopilib.mk
