TOPDIR=../..

SOURCES = \
	./cpp/Base64.cpp\
	./cpp/EventLoopRunner.cpp\
	./cpp/future.cpp\
	./cpp/hostname.cpp\
	./cpp/HttpParser.cpp\
	./cpp/HttpServerConnection.cpp\
	./cpp/HttpUtil.cpp\
	./cpp/http_parser.cpp\
	./cpp/json.cpp\
	./cpp/json_binary_reader.cpp\
	./cpp/json_binary_writer.cpp\
	./cpp/json_parser.cpp\
	./cpp/json_pointer.cpp\
	./cpp/json_serializer.cpp\
	./cpp/leb128.cpp\
	./cpp/llvm/ConvertUTF.cpp\
	./cpp/llvm/ConvertUTFWrapper.cpp\
	./cpp/llvm/ErrorHandling.cpp\
	./cpp/llvm/Hashing.cpp\
	./cpp/llvm/NativeFormatting.cpp\
	./cpp/llvm/Path.cpp\
	./cpp/llvm/raw_ostream.cpp\
	./cpp/llvm/raw_os_ostream.cpp\
	./cpp/llvm/SmallPtrSet.cpp\
	./cpp/llvm/SmallVector.cpp\
	./cpp/llvm/StringExtras.cpp\
	./cpp/llvm/StringMap.cpp\
	./cpp/llvm/StringRef.cpp\
	./cpp/llvm/Twine.cpp\
	./cpp/memory.cpp\
	./cpp/raw_istream.cpp\
	./cpp/raw_socket_istream.cpp\
	./cpp/raw_socket_ostream.cpp\
	./cpp/raw_uv_ostream.cpp\
	./cpp/SafeThread.cpp\
	./cpp/sha1.cpp\
	./cpp/SocketError.cpp\
	./cpp/TCPAcceptor.cpp\
	./cpp/TCPConnector.cpp\
	./cpp/TCPConnector_parallel.cpp\
	./cpp/TCPStream.cpp\
	./cpp/timestamp.cpp\
	./cpp/UDPClient.cpp\
	./cpp/uv/Async.cpp\
	./cpp/uv/Check.cpp\
	./cpp/uv/FsEvent.cpp\
	./cpp/uv/GetAddrInfo.cpp\
	./cpp/uv/GetNameInfo.cpp\
	./cpp/uv/Handle.cpp\
	./cpp/uv/Idle.cpp\
	./cpp/uv/Loop.cpp\
	./cpp/uv/NameToAddr.cpp\
	./cpp/uv/NetworkStream.cpp\
	./cpp/uv/Pipe.cpp\
	./cpp/uv/Poll.cpp\
	./cpp/uv/Prepare.cpp\
	./cpp/uv/Process.cpp\
	./cpp/uv/Signal.cpp\
	./cpp/uv/Stream.cpp\
	./cpp/uv/Tcp.cpp\
	./cpp/uv/Timer.cpp\
	./cpp/uv/Tty.cpp\
	./cpp/uv/Udp.cpp\
	./cpp/uv/Work.cpp\
	./cpp/WebSocket.cpp\
	./cpp/WebSocketServer.cpp\
	./libuv/fs-poll.cpp\
	./libuv/inet.cpp\
	./libuv/threadpool.cpp


TARGET=wpiutilsim

LOCAL_CFLAGS += -Iinclude -Ilibuv

include $(TOPDIR)/makefiles/buildlib.mk
