#!/bin/bash

ssh lvuser@10.14.25.2 "rm -f FRCUserProgram"
scp build/exe/frcUserProgram/frcUserProgram lvuser@10.14.25.2:/home/lvuser/FRCUserProgram
scp bunny2018/robot.dat lvuser@10.14.25.2:/home/lvuser/
