#!/bin/bash

TELEOPTIME=120
AUTOTIME=15
DISABLEDTIME=30
STARTTIME=5
TESTTIME=0

if [ $1 == "--gui" ]; then
    GUI=--simscreen
    shift
fi

rootdir=$(git rev-parse --show-toplevel)
cd $rootdir

if [ $# -lt 2 ]; then
    echo Expected at least two arguments, the name of the robot and the mode
    echo An optional third argument can be the simulator event file
    echo The mode should be 'auto', 'teleop'
   exit 1
fi

FLAGS=""
if [ $# -eq 3 ]; then
    FLAGS="--events robots/$1/sims/$3"
fi

legal=NO
if [ $2 == 'auto' ]; then
    legal=YES
    echo Running auto mode
    exec makebuild/SIMULATOR/Debug/ranseur/$1 --auto $AUTOTIME --oper 0 --start $STARTTIME --test 0 $FLAGS $GUI
fi

if [ $2 == 'teleop' ]; then
    legal=YES
    echo Running teleop mode
    exec makebuild/SIMULATOR/Debug/ranseur/$1 --auto 0 --oper $TELEOPTIME --start $STARTTIME --test 0 $FLAGS $GUI
fi

if [ $2 == 'both' ]; then
    legal=YES
    echo Running teleop mode
    exec makebuild/SIMULATOR/Debug/ranseur/$1 --auto $AUTOTIME --oper $TELEOPTIME --start $STARTTIME --test 0 $FLAGS $GUI
fi

if [ legal == 'NO' ]; then
    echo "Invalid mode, must be 'auto' or 'teleop'"
    exit 1
fi
