#!/bin/bash

AUTOTIME=15
OPERTIME=120

if [ $1 == "--gui" ]; then
    GUI=--simscreen
    shift
elif [ $1 == "--autotime" ]; then
    shift
    AUTOTIME=$1
    shift
elif [ $1 == "--opertime" ]; then
     shift
     OPERTIME=$1
     shift
fi

rootdir=$(git rev-parse --show-toplevel)
cd $rootdir

if [ $# -lt 2 ]; then
    echo Expected at least two arguments, the name of the robot and the mode
    echo An optional third argument can be the simulator event file
    echo The mode should be 'auto', 'teleop'
   exit 1
fi

FLAGS=""
if [ $# -eq 3 ]; then
    FLAGS="--events robots/$1/sims/$3"
fi

legal=NO
if [ $2 == 'auto' ]; then
    legal=YES
    echo Running auto mode
    exec makebuild/SIMULATOR/Debug/ranseur/$1 --auto $AUTOTIME --oper 0 --start 0 --test 0 $FLAGS $GUI
fi

if [ $2 == 'teleop' ]; then
    legal=YES
    echo Running teleop mode
    exec makebuild/SIMULATOR/Debug/ranseur/$1 --auto 0 --oper $OPERTIME --start 0 --test 0 $FLAGS $GUI
fi

if [ $2 == 'both' ]; then
    legal=YES
    echo Running teleop mode
    exec makebuild/SIMULATOR/Debug/ranseur/$1 --auto AUTOTIME --oper $OPERTIME --start 0 --test 0 $FLAGS $GUI
fi

if [ legal == 'NO' ]; then
    echo "Invalid mode, must be 'auto' or 'teleop'"
    exit 1
fi
