TOPDIR=../..

SOURCES = \
	cpp/DriverStation.cpp\
	cpp/Encoder.cpp\
	cpp/GenericHID.cpp\
	cpp/GPG3MotorController.cpp\
	cpp/I2C.cpp\
	cpp/Joystick.cpp\
	cpp/RobotBase.cpp\
	cpp/SampleRobot.cpp\
	cpp/SerialPort.cpp\
	cpp/Servo.cpp\
	cpp/Timer.cpp\
	cpp/DigitalOutput.cpp\
	cpp/AnalogOutput.cpp\
	cpp/XboxController.cpp\
	cpp/smartdashboard/NamedSendable.cpp\
	cpp/smartdashboard/SendableBase.cpp\
	cpp/smartdashboard/SendableBuilderImpl.cpp\
	cpp/smartdashboard/SendableChooserBase.cpp\
	cpp/smartdashboard/SmartDashboard.cpp\
	cpp/livewindow/LiveWindow.cpp\
	cpp/livewindow/LiveWindowSendable.cpp

TARGET=wpilib

LOCAL_CFLAGS=-Iinclude

NEED_XEROMISC=true
NEED_GOPIGO3HW=true
NEED_WPIUTIL=true
NEED_NETWORKTABLES=true

include $(TOPDIR)/makefiles/buildlib.mk

