#
# makefile for the misc library
#

#
# define our target library
#
TARGET=misc.a

#
# define the source code files
#
SRC = \
	TcpClientSocket.cpp

# message_logger.cpp

ifndef TESTS
TESTS =
endif

#
# include a central make file that defines our compilation recipe
#
include ../../../makefiles/compilelib.mk
