TOPDIR=../..

SOURCES = \
	droidScreenVisualizer.cpp\
	droidSimulator.cpp\
	OIModel.cpp\

TARGET=droidsim

NEED_WPILIB=true
NEED_CTRE=true
NEED_NAVX=true
NEED_XEROMISC=true
NEED_MODELS=true
NEED_REV=true
LOCAL_CFLAGS +=

include $(TOPDIR)/makefiles/buildlib.mk

