TOPDIR=../..

SOURCES = \
	Bunny2018ScreenVisualizer.cpp\
	Bunny2018Simulator.cpp\
	CollectorModel.cpp\
	HopperModel.cpp\
	OIModel.cpp\
	SorterModel.cpp

TARGET=bunny2018sim

NEED_WPILIB=true
NEED_CTRE=true
NEED_NAVX=true
NEED_XEROMISC=true

LOCAL_CFLAGS +=

include $(TOPDIR)/makefiles/buildlib.mk

