TOPDIR=../..

SOURCES = \
	./src/rev/CANEncoder.cpp\
	./src/rev/CANSparkMax.cpp\
	./src/rev/CANSparkMaxLowLevel.cpp\

TARGET=rev

NEED_WPIUTIL_2=true
NEED_NTCORE_2=true
NEED_WPILIB_2=true
NEED_HAL_2=true

LOCAL_CFLAGS += -Iinclude/rev

include $(TOPDIR)/makefiles/buildlib.mk
