SOURCES = \
	Kinematics.cpp\
	MessageDestFile.cpp\
	MessageDestSeqFile.cpp\
	MessageLogger.cpp\
	MessageLoggerData.cpp\
	PIDCtrl.cpp\
	SettingsParser.cpp\
	StallMonitor.cpp\
	TrapezoidalProfile.cpp

TARGET=gopigo3xeromisc

LOCAL_CFLAGS = -I../gopigo3/gopigo3frc -I../xeromath

include ../makefiles/gopilib.mk
