TOPDIR=../..

SOURCES = \
	$$RobotName$$ScreenVisualizer.cpp\
	$$RobotName$$Simulator.cpp\
	OIModel.cpp\

TARGET=$$robotname$$sim

NEED_WPILIB=true
NEED_CTRE=true
NEED_NAVX=true
NEED_XEROMISC=true
NEED_MODELS=true

LOCAL_CFLAGS +=

include $(TOPDIR)/makefiles/buildlib.mk

