TOPDIR=../..

SOURCES = \
	./src/ctre/phoenix/MotorControl/IMotorController.cpp

TARGET=ctre

NEED_WPIUTIL=true
NEED_NTCORE=true
NEED_WPILIB=true
NEED_HAL=true

LOCAL_CFLAGS += -Iinclude -Iinclude/ctre

include $(TOPDIR)/makefiles/buildlib.mk

