TOPDIR=../..

SOURCES = \
	./src/ctre/phoenix/MotorControl/IMotorController.cpp

TARGET=ctre

NEED_WPIUTIL_2=true
NEED_NTCORE_2=true
NEED_WPILIB_2=true
NEED_HAL_2=true

LOCAL_CFLAGS += -Iinclude -Iinclude/ctre

include $(TOPDIR)/makefiles/buildlib.mk

