TOPDIR=../..

SOURCES = \
	RanseurScreenVisualizer.cpp\
	RanseurSimulator.cpp\
	OIModel.cpp\
	TubManipulatorModel.cpp\
	BunnyArmModel.cpp\
	RanseurVision.cpp

TARGET=ranseursim

NEED_WPILIB=true
NEED_WPIUTIL=true
NEED_CTRE=true
NEED_REV=true
NEED_NAVX=true
NEED_XEROMISC=true
NEED_MODELS=true
NEED_NETWORKTABLES=true

LOCAL_CFLAGS +=

include $(TOPDIR)/makefiles/buildlib.mk

