TOPDIR=../..

SOURCES = \
	./frc/DigitalInput.cpp\
	./frc/DIJoystickManager.cpp\
	./frc/DriverStation.cpp\
	./frc/Encoder.cpp\
	./frc/PrintVisualizer.cpp\
	./frc/RobotSimBase.cpp\
	./frc/SampleRobot.cpp\
	./frc/ScreenVisualizer.cpp\
	./frc/SimulatedObject.cpp\
	./frc/smartdashboard/SmartDashboard.cpp\
	./frc/Solenoid.cpp\
	./frc/SubsystemModel.cpp\
	./frc/TankDriveModel.cpp\
	./frc/Timer.cpp\
	./frc/VictorSP.cpp

TARGET = wpilibsim

LOCAL_CFLAGS += -I. -I$(TOPDIR)/xeromisc -I$(TOPDIR)/simulator/ctresim -I$(TOPDIR)/simulator/navxsim -I$(TOPDIR)/xeromath

include $(TOPDIR)/makefiles/buildlib.mk


