TOPDIR=../..

SOURCES = \
	ActionSequence.cpp\
	ControllerBase.cpp\
	DelayAction.cpp\
	DispatchAction.cpp\
	DriverGamepad.cpp\
	OIDevice.cpp\
	OIOutputAction.cpp\
	OISubsystem.cpp\
	ParallelAction.cpp\
	Robot.cpp\
	RobotSubsystem.cpp\
	Subsystem.cpp\
	TCS34725ColorSensor.cpp\
	TeleopController.cpp\
	MessageListener/MessageListener.cpp\
	tankdrive/TankDrive.cpp\
	tankdrive/TankDriveDistanceAction.cpp\
	tankdrive/TankDriveVelocityAction.cpp\
	tankdrive/TankDriveCharAction.cpp\
	tankdrive/TankDriveAngleAction.cpp\
	tankdrive/TankDriveAngleCharAction.cpp\
	tankdrive/TankDrivePowerAction.cpp\
	tankdrive/TankDriveTimedPowerAction.cpp\
	tankdrive/TankDriveFollowPathAction.cpp\
	singlemotorsubsystem/SingleMotorPowerAction.cpp\
	singlemotorsubsystem/SingleMotorSubsystem.cpp\
	lifter/Lifter.cpp\
	lifter/LifterCalibrateAction.cpp\
	lifter/LifterGoToHeightAction.cpp\
	lifter/LifterPowerAction.cpp

TARGET=xerobase

NEED_WPIUTIL=true
NEED_WPILIB=true
NEED_NAVX=true
NEED_CTRE=true
NEED_NETWORKTABLES=true
NEED_XEROMISC=true

LOCAL_CFLAGS = -I.


include $(TOPDIR)/makefiles/buildlib.mk

