TOPDIR=../..

SOURCES = \
	SwerveSimulator.cpp

TARGET=phasersim

NEED_WPILIB=true
NEED_CTRE=true
NEED_NAVX=true
NEED_XEROMISC=true
NEED_MODELS=true
NEED_SPARK=true

LOCAL_CFLAGS +=

include $(TOPDIR)/makefiles/buildlib.mk

