#!/bin/bash

mkdir -p output

pushd ranseur
#make clean
#make > ../output/ranseur.log 2>&1
popd

pushd gopigo3frc
make clean
make > ../output/gopigo3frc.log 2>&1
popd

pushd gopigo3xerobasic
make clean
make > ../output/gopigo3xerobasic.log 2>&1
popd

pushd gopigo3xerofull
make clean
make > ../output/gopigo3xerofull.log  2>&1
popd

