SOURCES = \
	AHRS.cpp\
	ContinuousAngleTracker.cpp\
	InertialDataIntegrator.cpp\
	OffsetTracker.cpp\
	SerialIO.cpp\
	SerialPort.cpp\
	TimeStamp.cpp

TARGET=gopigo3navx

LOCAL_CFLAGS=-I.

include ../../makefiles/gopilib.mk
