SOURCES = \
	AHRS.cpp\
	ContinuousAngleTracker.cpp\
	InertialDataIntegrator.cpp\
	OffsetTracker.cpp\
	RegisterIO.cpp\
	RegisterIOI2C.cpp\
	RegisterIOSPI.cpp\
	SerialIO.cpp

TARGET=gopigo3navx

LOCAL_CFLAGS=-I../gopigo3hw -I../../xeromisc -I. -I.. -I../frc

include ../../makefiles/gopilib.mk
