SOURCES = \
	DriverStation.cpp\
	Encoder.cpp\
	GenericHID.cpp\
	GPG3MotorController.cpp\
	I2C.cpp\
	Joystick.cpp\
	RobotBase.cpp\
	SampleRobot.cpp\
	SerialPort.cpp\
	Servo.cpp\
	Timer.cpp\
	DigitalOutput.cpp\
	AnalogOutput.cpp\
	ctre/phoenix/MotorControl/CAN/TalonSRX.cpp\
	smartdashboard/SmartDashboard.cpp

TARGET=wpilib

LOCAL_CFLAGS=-I../gopigo3hw -I../../xeromisc -I.

include ../../makefiles/gopilib.mk
