TOPDIR=../..

SOURCES = \
	sim/Accelerometer.cpp\
	sim/AddressableLED.cpp\
	sim/AnalogAccumulator.cpp\
	sim/AnalogGyro.cpp\
	sim/AnalogInput.cpp\
	sim/AnalogInternal.cpp\
	sim/AnalogOutput.cpp\
	sim/AnalogTrigger.cpp\
	sim/CallbackStore.cpp\
	sim/CAN.cpp\
	sim/CANAPI.cpp\
	sim/Compressor.cpp\
	sim/Constants.cpp\
	sim/Counter.cpp\
	sim/DigitalInternal.cpp\
	sim/DIO.cpp\
	sim/DMA.cpp\
	sim/DriverStation.cpp\
	sim/DutyCycle.cpp\
	sim/Encoder.cpp\
	sim/Extensions.cpp\
	sim/HAL.cpp\
	sim/HALInitializer.cpp\
	sim/I2C.cpp\
	sim/Interrupts.cpp\
	sim/mockdata/AccelerometerData.cpp\
	sim/mockdata/AddressableLEDData.cpp\
	sim/mockdata/AnalogGyroData.cpp\
	sim/mockdata/AnalogInData.cpp\
	sim/mockdata/AnalogOutData.cpp\
	sim/mockdata/AnalogTriggerData.cpp\
	sim/mockdata/CanDataInternal.cpp\
	sim/mockdata/DigitalPWMData.cpp\
	sim/mockdata/DIOData.cpp\
	sim/mockdata/DriverStationData.cpp\
	sim/mockdata/DutyCycleData.cpp\
	sim/mockdata/EncoderData.cpp\
	sim/mockdata/I2CData.cpp\
	sim/mockdata/PCMData.cpp\
	sim/mockdata/PDPData.cpp\
	sim/mockdata/PWMData.cpp\
	sim/mockdata/RelayData.cpp\
	sim/mockdata/RoboRioData.cpp\
	sim/mockdata/SimDeviceData.cpp\
	sim/mockdata/SPIAccelerometerData.cpp\
	sim/mockdata/SPIData.cpp\
	sim/MockHooks.cpp\
	sim/Notifier.cpp\
	sim/PDP.cpp\
	sim/Ports.cpp\
	sim/Power.cpp\
	sim/PWM.cpp\
	sim/Relay.cpp\
	sim/SerialPort.cpp\
	sim/SimDevice.cpp\
	sim/Solenoid.cpp\
	sim/SPI.cpp\
	sim/Threads.cpp


TARGET=hal

NEED_WPIUTIL=true

LOCAL_CFLAGS += -Iinclude -Ibuild -Isim2

include $(TOPDIR)/makefiles/buildlib.mk
