TOPDIR=../..

SOURCES = \
	PhaserScreenVisualizer.cpp\
	PhaserSimulator.cpp\
	OIModel.cpp\
	HatchHolderModel.cpp\
	CargoHolderModel.cpp\
	HatchIntakeModel.cpp\
	CargoIntakeModel.cpp\
	ClimberModel.cpp

TARGET=phasersim

NEED_WPILIB=true
NEED_CTRE=true
NEED_NAVX=true
NEED_XEROMISC=true
NEED_MODELS=true

LOCAL_CFLAGS +=

include $(TOPDIR)/makefiles/buildlib.mk

