TOPDIR=../..

SOURCES = \
	PhaserScreenVisualizer.cpp\
	PhaserSimulator.cpp

TARGET=phasersim

NEED_WPILIB=true
NEED_CTRE=true
NEED_NAVX=true
NEED_XEROMATH=true
NEED_XEROMISC=true

LOCAL_CFLAGS +=

include $(TOPDIR)/makefiles/buildlib.mk

