#!/bin/sh

# This script should be installed in /home/pi.  It's executed at boot time + when camera service is started.
# 5 second wait is added because camera may not be ready at boot time.

echo "Waiting 5 seconds..."
sleep 5

# TEMPORARY UNTIL 2019.2.1
export LD_LIBRARY_PATH=/home/pi/2019.2.1_preview/cpp-multiCameraServer/lib

# Run vision binary
exec ./vision_phaser2019.exe
