TOPDIR=../..

SOURCES = \
	CSVData.cpp\
    FlagManager.cpp\
	Kinematics.cpp\
	MessageDestFile.cpp\
	MessageDestSeqFile.cpp\
	MessageLogger.cpp\
	PIDACtrl.cpp\
	PIDCtrl.cpp\
	Point.cpp\
	PointAngle.cpp\
	Polar.cpp\
	QuadraticSolver.cpp\
	SettingsParser.cpp\
	StallMonitor.cpp\
	TrapezoidalProfile.cpp\
	XeroPathManager.cpp

TARGET=xeromisc

LOCAL_CFLAGS += 

include $(TOPDIR)/makefiles/buildlib.mk

