TOPDIR=../..

SOURCES = \
	Kinematics.cpp\
	MessageDestFile.cpp\
	MessageDestSeqFile.cpp\
	MessageLogger.cpp\
	MessageLoggerData.cpp\
	PIDACtrl.cpp\
	PIDCtrl.cpp\
	SettingsParser.cpp\
	StallMonitor.cpp\
	TrapezoidalProfile.cpp\
	XeroPath.cpp\
	XeroPathManager.cpp\
	XeroPathReader.cpp

TARGET=xeromisc

NEED_WPILIB=true
NEED_XEROMATH=true

LOCAL_CFLAGS += 

include $(TOPDIR)/makefiles/buildlib.mk

