name: CI
on: [push, pull_request]

env:
  MAX_LOAD: 3   # limit load average to avoid running out of memory

jobs:
  roborio:
    name: RoboRio
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Install toolchain
      run: ./gradlew installRoboRioToolchain
      
    - name: Build robot code
      run: ./gradlew build
      
      
  simulator:
    name: Simulator
    runs-on: ubuntu-latest

    strategy: 
      matrix: 
        robot: [droid]
        configuration: [Debug, ASan]

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: sudo apt-get install libncurses-dev libopencv-highgui-dev

    - name: Build robot code
      working-directory: robots/${{ matrix.robot }}
      run: make CONFIG=${{ matrix.configuration }} PLATFORM=SIM2 --max-load $MAX_LOAD

    - name: Deploy resources
      working-directory: robots/${{ matrix.robot }}
      run: make CONFIG=${{ matrix.configuration }} PLATFORM=SIM2 deploy

#     - name: Run simulator (auto)
#       run: ./runsim2 ${{ matrix.robot }} automode7

#     - name: Run simulator (teleop)
#       run: ./runsim2 ${{ matrix.robot }} teleop


  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build xeromisc
      working-directory: xerolibs/xeromisc
      run: make CONFIG=Debug PLATFORM=SIMULATOR --max-load $MAX_LOAD

    - name: Build xeromisctest
      working-directory: xerolibs/xeromisctest
      run: make CONFIG=Debug --max-load $MAX_LOAD

    - name: Run xeromisctest
      working-directory: xerolibs/xeromisctest
      run: ./xeromisctest
